jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@83c99634a87ca49d42c93eaf25c6fe2e00de7084

name: Contributors

on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch: ~
