jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        uses: JoshuaKGoldberg/all-contributors-auto-action@cc068bce7f3be6cfb9bf80178478a0ad6dd38b58

name: Contributors

on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch: ~
